FROM node:14-slim

WORKDIR /alpaca_twins/
COPY ./package.json /alpaca_twins/
COPY ./package-lock.json /alpaca_twins/

RUN apt-get update \
  && apt-get install python3 make gcc g++ -y \
  && npm install \
  && npm install @discordjs/opus opusscript \
  && apt-get remove make gcc g++  -y\
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

CMD ["node", "dead.js"]

COPY ./build/dead.js /alpaca_twins/
